.TH "ros-delete" "1" "" "" ""
.nh \" Turn off hyphenation by default.
.PP
ros\-delete \-
.SH Synopsis
.PP
\f[B]ros [options] delete\f[] [\-\-dump] targets...
.SH Description
.PP
Delete the specified installed targets from roswell.
A target can be an implementation/version, or a name of the dumped image
saved by roswell when \-\-dump is specified.
.SH SEE ALSO
.PP
\f[I]ros\f[](1)
.SH AUTHORS
SANO Masatoshi.
