.TH "ros-emacs" "1" "" "" ""
.nh \" Turn off hyphenation by default.
.PP
ros\-emacs \- launch Emacs with Slime
.SH Synopsis
.PP
\f[B]ros [options] emacs\f[] [ARGS...]
.SH Description
.PP
Launches Emacs with a Slime(https://common\-lisp.net/project/slime/)
buffer opened, which is connected to the back\-end lisp implementation
of roswell.
Additional arguments are passed to emacs.
.SH SEE ALSO
.PP
\f[I]ros\f[](1), \f[I]emacs\f[](1)
.SH AUTHORS
Roswell Project Team.
