.SH name
.PP
ros\-list \- list the materials installed by roswell
.SH synopsis
.PP
\f[B]ros list [type] [options]\f[]
.SH description
.PP
\f[B]ros list\f[] shows the list of the materials installed by roswell.
installed
.PP
:List implementations that already installed
dump
.PP
:List dumped
versions
.PP
:List installable versions(experimental)
.SH SEE ALSO
.PP
\f[I]sbcl\f[](1) \f[I]ros\f[](1)
.SH Author
.PP
SANO Masatoshi
