.TH "ros-build" "1" "" "" ""
.nh \" Turn off hyphenation by default.
.PP
ros\-build \- Shortcut to "ros dump executable" # synopsis
.PP
\f[B]ros [options] build\f[]
.PP
Equivalent to calling \f[C]ros\ dump\ executable\ <file>\f[].
.SH description
.SH SEE ALSO
.PP
\f[I]ros\f[](1)
.SH AUTHORS
Roswell Project Team.
