.TH "ros-delete" "1" "" "" ""
.nh \" Turn off hyphenation by default.
.PP
ros\-delete \-
.SH synopsis
.PP
\f[B]ros delete\f[] ARGS...
.PP
Slightly complex arguments.
.SS ros delete dump IMAGES...
.PP
Whem ARGS starts with \f[C]dump\f[], it considers the remaining args as
the names for the dumped images.
It then deletes the image with the given name, if it exists.
.PP
The deletion happens only to the images compatible with the current lisp
implementation/version.
For example, when ccl\-bin/1.10 and sbcl\-bin/1.3.1 both have images
named X, and if the current lisp in use is sbcl\-bin/1.3.1, then
\f[C]ros\ delete\ dump\ X\f[] removes sbcl\-bin/1.3.1/X only.
.SS ros delete IMPLS...
.PP
When the first argument is not \f[C]dump\f[], then the arguments are
treated as a list of installed implementations.
.PP
If a name of some implementation is given without version specifiers,
e.g.
sbcl\-bin, then it removes all instances (versions) of sbcl\-bin.
.PP
If a version is specified, then it removes only the specified instance.
.SH description
.SH SEE ALSO
.PP
\f[I]ros\f[](1)
.SH AUTHORS
Roswell Project Team.
