.TH "ros-asdf" "1" "" "" ""
.nh \" Turn off hyphenation by default.
.PP
ros\-asdf \- # synopsis
.PP
\f[B]ros [options] asdf [subcommand]\f[]
.SH description
.PP
\f[B]ros asdf\f[] install and manage
ASDF(https://common\-lisp.net/project/asdf/)
.SH SEE ALSO
.PP
\f[I]ros\f[](1)
.SH AUTHORS
Roswell Project Team.
