.TH "ros-list" "1" "" "" ""
.nh \" Turn off hyphenation by default.
.PP
ros\-list \- list the materials installed by roswell
.SH Synopsis
.PP
\f[B]ros list [type] [options]\f[]
.SH Description
.PP
\f[B]ros list\f[] shows the list of the materials installed by roswell.
.TP
.B installed
List implementations that already installed
.RS
.RE
.TP
.B dump
List dumped
.RS
.RE
.TP
.B versions
List installable versions(experimental)
.RS
.RE
.SH SEE ALSO
.PP
\f[I]sbcl\f[](1) \f[I]ros\f[](1)
.SH AUTHORS
Roswell Project Team.
