.TH "ros-run" "1" "" "" ""
.nh \" Turn off hyphenation by default.
.PP
ros-run - start a REPL # Synopsis
.PP
\f[B]ros [options] run\f[]
.SH Description
.PP
Processes the given options and start a REPL using the currently
effective lisp implementation set by \f[I]ros-use\f[](1).
.SH SEE ALSO
.PP
\f[I]ros\f[](1)
.SH AUTHORS
Roswell Project Team.
