Document: roswell
Title: Debian roswell Manual
Author: <insert document author here>
Abstract: This manual describes what roswell is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/roswell/roswell.sgml.gz

Format: postscript
Files: /usr/share/doc/roswell/roswell.ps.gz

Format: text
Files: /usr/share/doc/roswell/roswell.text.gz

Format: HTML
Index: /usr/share/doc/roswell/html/index.html
Files: /usr/share/doc/roswell/html/*.html
