FROM alpine:3.20
run apk add --no-cache \
	alpine-sdk automake autoconf curl-dev bash linux-headers \
	curl-static nghttp2-static openssl-libs-static brotli-static zlib-static zstd-static c-ares-static \
	libidn2-static libunistring-static libpsl-static;
